### PR TITLE
Fix breakpoints on Windows by replacing \ with / in file paths

### PR DESCRIPTION
**Pull request by b-szypelow**
Fix for #25

### CODE REVIEW

**Comment by raix** [comment]
Thanks @b-szypelow!
So perl expects unix path separators on windows? it's odd but if it works for the windows users I'd be happy to merge

**Comment by b-szypelow** [comment]
Although \ is traditional path separator in Windows, modern versions accept both \ and / - that's why it works.
Thanks for merging.

**Comment by raix** [comment]
@b-szypelow just released v0.2.2 adding this

**Comment by b-szypelow** [comment]
@raix That's weird - I've upgraded and it doesn't seem to contain the patch. Likely the `out` directory of the release contains old compilation.

**Comment by raix** [comment]
@b-szypelow thanks for catching 0.2.3 is out

**Pull request merged**
