### PR TITLE
Fix for fatal warning-exceptions; streamcatcher debug output channel

### PR DESCRIPTION
**Pull request by hoehrmann**
* fixes https://github.com/raix/vscode-perl-debug/issues/52
* make several classes actual EventEmitters
* Use new eventing setup to bubble events up into the extension
* ... and from there into an output channel window if users wish
* Minor cleanup / additions in readme.md

### CODE REVIEW

**Comment by raix** [comment]
Thanks @hoehrmann looks great - just fyi, if you use semantic commit messages in this repository the extension should be released when merged :)

**Comment by raix** [comment]
Hmm doesn't seem to be able to merge yet - not sure if it's a github issue

**Comment by hoehrmann** [comment]
@raix: I can try to format commit messages accordingly, but don't promise anything... And yeah, I am having issues with Github aswell at the moment, "ajax" stuff taking forever to load kind of problems. Like, the "preview" for this comment would not load just now...

**Pull request merged**
